### ISSUE TITLE
Init task excludes transitive dependencies by default

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#123]
Given the following `glide.yaml`:

```
package: .
import:
- package: github.com/mvdan/xurls
  version: 1.1.0
testImport:
- package: github.com/stretchr/testify
  version: 1.1.4
```

And this `glide.lock`:

```
hash: 806deb3bb1bb02051f152c49856cac37224f623247742a1b8c028b38dff21aef
updated: 2017-06-03T12:38:37.338393246-04:00
imports:
- name: github.com/mvdan/xurls
  version: d315b61cf6727664f310fa87b3197e9faf2a8513
testImports:
- name: github.com/stretchr/testify
  version: 69483b4bd14f5845b5a1e55bca19e954e827f1d0
```

the resulting dependencies block generate by the `init` task of the plugin sets transitive dependencies to `false`:

```
dependencies {
    golang {
        build name:'github.com/mvdan/xurls', version:'d315b61cf6727664f310fa87b3197e9faf2a8513', transitive:false
        test name:'github.com/stretchr/testify', version:'69483b4bd14f5845b5a1e55bca19e954e827f1d0', transitive:false
    }
}
```

The default in Gradle is to resolve transitive dependencies. The plugin should use the same default. In this case `transitive:true` or leave off the statement.
