### ISSUE TITLE
init task generates inconsistent subpackage declaration

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#188]
Given the following `glide.lock`:

```
hash: 806deb3bb1bb02051f152c49856cac37224f623247742a1b8c028b38dff21aef
updated: 2018-01-08T20:54:38.326434-07:00
imports:
- name: github.com/mvdan/xurls
  version: d315b61cf6727664f310fa87b3197e9faf2a8513
testImports:
- name: github.com/davecgh/go-spew
  version: 6d212800a42e8ab5c146b8ace3490ee17e5225f9
  subpackages:
  - spew
- name: github.com/pmezard/go-difflib
  version: d8ed2627bdf02c080bf22230dbb337003b7aba2d
  subpackages:
  - difflib
- name: github.com/stretchr/testify
  version: 69483b4bd14f5845b5a1e55bca19e954e827f1d0
  subpackages:
  - assert
```

Running `gradle init` generates the following dependencies declaration:

```
dependencies {
    golang {
        build(['name':'github.com/mvdan/xurls', 'version':'d315b61cf6727664f310fa87b3197e9faf2a8513', 'transitive':false])
        test(['name':'github.com/davecgh/go-spew', 'version':'6d212800a42e8ab5c146b8ace3490ee17e5225f9', 'subpackages':['.', 'spew'], 'transitive':false])
        test(['name':'github.com/pmezard/go-difflib', 'version':'d8ed2627bdf02c080bf22230dbb337003b7aba2d', 'subpackages':['difflib', '.'], 'transitive':false])
        test(['name':'github.com/stretchr/testify', 'version':'69483b4bd14f5845b5a1e55bca19e954e827f1d0', 'subpackages':['.', 'assert'], 'transitive':false])
    }
}
```

1. It looks like the subpackage declarations are stored as unordered Set. It looks a bit weird to see `.` first and then the subpackage and sometimes the other way around.
2. I believe `.` is not needed at all.
