### ISSUE TITLE
Cannot recoginze vendor/github.com/ServiceComb/auth when I use vendor.json

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#214]
你好，咨询个问题，我有个依赖包里包含vendor目录，目录下存在vendor.json文件以及第三方包，即

```
vendor
   ------vendor.json
   ------github.com/...
```
vendor.json部分内容如下
```
{
      "checksumSHA1": "1q1S5NlaZd0rxHUGyCse7UWQmCw=",
      "origin": "vendor/github.com/ServiceComb/auth",
      "path": "github.com/ServiceComb/auth",
      "revision": ""
},
{
	"checksumSHA1": "3AGBQ10ptcUKICwXXXCQwup+gSc=",
	"origin": "vendor/github.com/ServiceComb/auth/third_party/forked/datastream/aws",
	"path": "github.com/ServiceComb/auth/third_party/forked/datastream/aws",
	"revision": ""
},
```

我在构建时，报错，Cannot recoginze vendor/github.com/ServiceComb/auth

有两个问题咨询下：
1.构建时取的版本是否是按照vendor.json中定义的版本还是直接使用vendor中的版本?
2.构建时报错是什么原因导致的？

非常感谢！

**Comment by JackTiger** [comment]
另外咨询个问题：(git操作问题)
1.我使用gogradle在本地执行构建，依赖A仓库的test分支，本地全局缓存中下载了A仓库的test分支
2.远程A仓库test分支被删除，本地依赖A仓库的其他分支，使用gogradle执行构建失败，提示git操作失败
使用之前某个远程分支被删除导致本地git fetch失败

这个问题可否在git fetch之前，先执行下面的命令
git remote prune origin

删除本地存在但远程已被删除的分支，再执行git fetch

**Comment by blindpirate** [comment]
当前的实现假设`origin`的格式是：

```
{
                        "checksumSHA1": "CujWu7+PWlZSX5+zAPJH91O5AVQ=",
                        "origin": "github.com/docker/distribution/vendor/github.com/Sirupsen/logrus",
                        "path": "github.com/Sirupsen/logrus",
                        "revision": "0700fa570d7bcc1b3e46ee127c4489fd25f4daa3",
                        "revisionTime": "2017-03-21T17:14:25Z"
                    },
```

但是你给出的`vendor.json`中的`origin`看上去有点奇怪，不知道能否给个示例，哪些仓库用的这个格式？

> 构建时取的版本是否是按照vendor.json中定义的版本还是直接使用vendor中的版本?

都用。合并二者：https://github.com/gogradle/gogradle/blob/master/docs/dependency-management-cn.md#%E4%BC%A0%E9%80%92%E6%80%A7%E4%BE%9D%E8%B5%96

> 这个问题可否在git fetch之前，先执行下面的命令
> git remote prune origin

可以考虑增加这样的容错处理。

**Comment by JackTiger** [comment]
好的，谢谢！

建议在下个版本把下面这个方案加上。

```
这个问题可否在git fetch之前，先执行下面的命令
git remote prune origin

可以考虑增加这样的容错处理。
```

vendor.json的问题，可能是内部使用问题，我在github上找找有没有例子。

**Comment by JackTiger** [comment]
@blindpirate 
你好，我的依赖库有一个gogradle.lock文件，部分依赖如下：

```
	- name: "github.com/servicecomb/auth"
    host:
      name: "xxxx.xxxxx.com/xxxx/xxxx/xxxx/aaaaa"
      commit: "141fb5ce59f8898a37c1cdcda05b2a75096bb76e"
      url: "git@xxxx.xxxxx.com:xxxx/xxxx/xxxx/aaaaa.git"
      vcs: "git"
    vendorPath: "vendor/github.com/servicecomb/auth"
    transitive: false
```

我在构建时，提示如下错误;

```
Caused by: com.github.blindpirate.gogradle.core.exceptions.BuildException: Build failed due to exception of cmd: git log -1 --pretty=format:%ct vendor/github.com/ServiceComb/auth
```

看上去好奇怪，为啥回去判断vendor/github.com/ServiceComb/auth这个路径

**Comment by blindpirate** [comment]
`git log vendor/github.com/ServiceComb/auth`的目的是检查它被提交的时间，以便判断它是不是“最新”的，以及是否应该在冲突的解决中胜出。

**Comment by JackTiger** [comment]
好的，谢谢！我理解你的意思，但是为啥报错呢？我明天试下执行这个命令。

**Comment by JackTiger** [comment]
我上午试了这个命令，发现

`Caused by: com.github.blindpirate.gogradle.core.exceptions.BuildException: Build failed due to exception of cmd: git log -1 --pretty=format:%ct vendor/github.com/ServiceComb/auth`

执行上面这个命令返回的字符串为空


我使用git log -1 --pretty=format:%ct vendor/github.com/servicecomb/auth是可以拿到文件时间的，所以我怀疑是大小写的问题，git上传时对大小写不敏感。

**Comment by blindpirate** [comment]
看上去是大小写的问题，但是我觉得你好像说反了：git是区分大小写的（`git log -1 --pretty=format:%ct vendor/github.com/ServiceComb/auth`的本质是fork一个git进程然后把命令行参数传给它。git发现大小写不一致，就认为不存在），而Windows的NTFS是不区分的。git在windows上的实现是可以设置区分大小写的，但是显然在你们的环境中没有统一：如果仓库的文件名一致（一直是`ServiceComb/auth`或者一直是`servicecomb/auth`），那么这个问题就不会出现，参考：https://tonydeng.github.io/2015/10/21/capitalization-error-handing-in-git/

**Comment by JackTiger** [comment]
你好，咨询个问题：
我使用gogradle时，报下面的错误，而且在linux上会报错，不清楚啥原因：

`Caused by: com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException: vendor dependency k8s.io/apimachinery:code.xxxxxx.com/xxxxx/xxxx/xxxxx/aaaaaa: commit='4c83f9fe00bf8f2ddcbbd7eb7f01f442f792b198', urls=[git@code.xxxxxx.com:xxxx/xxxx/xxxxx/aaaaaa.git]/vendor/k8s.io/apimachinery/pkg/util/sets does not exist in transitive dependencies of code.xxxxxx.com/xxxxx/xxxx/xxxxx/aaaaaa#4c83f9fe00bf8f2ddcbbd7eb7f01f442f792b198`

**Comment by JackTiger** [comment]
我有个库，它里面的vendor路径是vendor/k8s.io/apimachinery/pkg/util/sets， gogradle解析路径时，k8s.io/apimachinery被认为是一个包，所以导致解析失败了，这个有方法解决吗？

**Comment by JackTiger** [comment]
我在windows上构建A时生成gogradle.lock时，内容如下：(可能由于代理原因，k8s.io/apimachinery没有被认为是一个包)

```
- name: "k8s.io/apimachinery/pkg/util/sets"
    host:
      name: "code.xxxx.com/xxxx/xxxx/xxxx/aaaaa"
      commit: "a4c33f595932507040a71edef95449fa87e3b505"
      url: "git@code.xxxx.com:xxxx/xxxx/xxxx/aaaaa.git"
      vcs: "git"
    vendorPath: "vendor/k8s.io/apimachinery/pkg/util/sets"
    transitive: false
```

我在另外一个机器上依赖A，执行构建，报错，
`Caused by: com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException: vendor dependency k8s.io/apimachinery:code.xxxx.com/xxxx/xxxx/xxxx/aaaaa: commit='4c83f9fe00bf8f2ddcbbd7eb7f01f442f792b198', urls=[git@code.xxxx.com:xxxx/xxxx/xxxx/aaaaa.git]/vendor/k8s.io/apimachinery/pkg/util/sets does not exist in transitive dependencies of code.xxxx.com/xxxx/xxxx/xxxx/aaaaa#4c83f9fe00bf8f2ddcbbd7eb7f01f442f792b198`

原因是，该机器上k8s.io/apimachinery被认为是一个包，这里有些奇怪，为啥不直接从A的gogradle里去取包，而是通过https的方式去查询vendor中的包结构，不是很理解？
